### ISSUE TITLE
Ignored partials that are used as plugin templates don't trigger the watcher

### ISSUE THREAD

**Issue by cearls** [static-dev/spike#40]
I'm using an ignored view (views/_page.sgr) as a plugin template and changes to this file aren't triggering the watcher.

@jescalan commented in gitter: so ignored files are ignored by the watcher unless they are added to webpack as dependencies of files

**Comment by jescalan** [comment]
Ok so I have been thinking about how we might be able to work this out. The issue is that spike typically tries to only recompile the files that are needed during the watch, and has a map itself of which files depend on which other files. However, the templates generate output independent of other files in the project, and plugins decide on the output they generate. So I'm not entirely sure what spike will do even if they are added to the watcher, but we shall see.

This line should enable us to add the template files to the watcher manually, going to test with this and see if this resolves the issue:

https://github.com/static-dev/spike-core/blob/master/lib/config.js#L150

**Comment by jescalan** [comment]
Ok so this has been solved with the latest round of updates to how single page templates are handled. The architecture change has been made and published to `spike-datocms` and `spike-contentful`. 🎉
