### ISSUE TITLE
Does it work with Webpack v2?

### ISSUE THREAD

**Issue by balupton** [static-dev/spike#51]
The current master of the spike website is on webpack v1 https://github.com/static-dev/spike-www/blob/e55f3c0143f9e53a9099762d80ec005059153ec4/package.json

**Comment by jescalan** [comment]
Hi @balupton! Yep, I just finished the (grueling) upgrade to v2 late last week. It's currently in prerelease while any bugs are ironed out. I'm running two production sites on it and it's working well so far. I'd expect a full release end of this week or next week.

You can use the v2 version with `npm i spike@next -g`. It is a breaking upgrade though, so using spike@next on an existing project will require a number of adjustments, which will be documented clearly in a migration guide and probably video before the stable release.

**Comment by heyivanvilla** [comment]
@jescalan I'm considering using Spike for a project, would you say it's safe to start working with the current version, or wait till you release the next version?

**Comment by jescalan** [comment]
It's safe to work with the current version for sure. I'd say it's also pretty safe to work with the next version as well, I have put out one production site on it already and am working on another right now.

The only situation where you might run into issues is if you are trying to do some serious custom functionality, and your site needs to be shipped within the next week or two, since I won't have as much time for dedicated support for the next couple weeks.

To get started with the next version, `npm i spike@next` and generate a new project. If you'd rather stick with the current one, that's totally fine though, and when the official release is out, it will include a migration guide.

**Comment by jescalan** [comment]
Closing since we have been on webpack latest in spike stable for quite a while not 😁
