### ISSUE TITLE
Suspending spike breaks reload

### ISSUE THREAD

**Issue by SevereOverfl0w** [static-dev/spike#70]
If I hit Ctrl-Z so I can free up my terminal to use vim or similar, the reload doesn't work until I run `fg` again.

**Comment by jescalan** [comment]
Hey sorry for the late response here -- I have no idea how to fix this and it certainly is not something that can be implemented in spike, since spike uses webpack's watcher. If you do need this to be fixed, I would try filing it in watchpack instead. Or just opening a new terminal tab when you need to do something else 😁
