### ISSUE TITLE
How do you minify images and place them in the public/img

### ISSUE THREAD

**Issue by maotora** [static-dev/spike#84]
Hello,

I have a problem that I don't know much about webpack. So, I cannot really understand how to use `imagemin` kind of libraries (img-loader, image-webpack-loader etc) with spike and produce minified images in `public/img` directory with their names.

I tried this code:

```js
    module: {
        rules: [{
            test: /\.(jpe?g|png|svg)$/i,
            use: [
                'url-loader?limit=10000',
                'img-loader'
            ]
        }]
    }
```

But this gave me a very strange output in `public/img/image_name.png` Where images where now javascript files containing path to a hashed image.

Like this:
![screenshot from 2017-12-18 14-15-56](https://user-images.githubusercontent.com/5174884/34103515-ff147be6-e3fd-11e7-9eeb-e0b2388c4971.png)

Now maybe this is very simple stuff but I cannot deal with that script hence no image displays.
I need to have an image output in `/public/img/` directory with image names like the ones present in `assets/img` directory.

Thanks for this awesome generator!

**Comment by jescalan** [comment]
Hey there! So right now there are some weird issues with the image loader that's causing it not work play along super well with spike, at least there were last time I checked. It hasn't been a priority for me to dig into this, because you can just run imageoptim on any exported images yourself quite easily, and each image only needs to be optimized once, so it's actually much faster for your builds that way.

If you wanted to try to fix this, you'd need to take out url loader. That's the loader giving you the path. Webpack is a javascript bundler, and what url-loader does is gives you a path output that can be required from a javascript file. You also want to make sure you are only running this in production build mode, or it will massively slow down your development by re-optimizing already optimized images over and over every time you make a change.
