### ISSUE TITLE
spike watch fails

### ISSUE THREAD

**Issue by maotora** [static-dev/spike#94]
Hi,

I've just experienced an issue when I run 

    spike watch

With new or old projects I get an error message saying;

```
node[1116]: ../src/node_file.cc:829:void node::fs::Stat(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `(argc) == (3)' failed.
 1: node::Abort() [node]
 2: 0x556455e719db [node]
 3: 0x556455ead49d [node]
 4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [node]
 5: 0x556456086f7d [node]
 6: 0x55645608738f [node]
 7: 0x6147828427d
[1]    1116 abort (core dumped)  spike watch
```
I am not sure if this is a Nodejs issue or Spike's.

Versions of programs I use;

```
node: v10.0.0
npm: 6.0.0
spike: 2.2.1
OS: ArchLinux
```

Thanks.

**Comment by jescalan** [comment]
That would be a node issue, unfortunately 😓

**Comment by maotora** [comment]
Any solution or suggestion?

**Comment by jescalan** [comment]
This seems like a fairly large problem with either your system or node installation. That trace points back to a C source file, which is what node is written with, to the `fs.Stat` function.

I am not an expert in node's internals, and this issue has nothing to do with spike, so that's just about as much as I can diagnose. If I ran into that issue, I might try downgrading to the LTS version of node and see if that works. The 10.0 release is brand new, and arch linux users are few and far in between.

**Comment by yzalvov** [comment]
Downgrade worked for me. thank you @jescalan !

**Comment by maotora** [comment]
Yes, I also had to downgrade to node V8.11.3 and was actually pleased to know that ArchLinux has separate packages for node V8, latest and V6.

They are all listed if you do

    pacman -Ss node

Thanks @jescalan
