### ISSUE TITLE
themes for spike

### ISSUE THREAD

**Issue by jbshirk** [static-dev/spike#96]
Maybe it's obvious for those who know about webpack, but practically all sites for SSGs have a section in their docs about themes, and often a repo of theme demos. I searched all over the spike site, and the github repo, and google for "spike themes" and can't find anything. Some good advice for a beginner moving from Hugo, Jekyll, etc. Would be a great help.

**Comment by EnMod** [comment]
I think the lack of theme documentation is due to the nature of Spike: it's focused on generating static sites for your specific purposes, and does its best to leave the user free to add their own plugins/features as they see fit.  The focus of Spike seems to be much less on creating blogs or themed sites (although you can certainly do that easily, [as I have](https://github.com/EnMod/noelquiles.com/tree/blog/)), and more on developing sites as you like with a minimal, clean base.

That said, there are various templates you can use with Spike, like [`spike-tpl-jekyll`](https://github.com/static-dev/spike-tpl-jekyll) (which aims to replicate Jekyll functionality) or any others that are developed for [Sprout](https://github.com/carrot/sprout).  This is as similar to "themes" as Spike gets I think.  The ["kitchen sink" template](https://github.com/static-dev/spike-tpl-kitchen-sink) has more examples of what the tool can do with templates.

**Comment by jescalan** [comment]
Thanks for the great response here @EnMod - all of this is for sure accurate.

I'd also add that spike is not a beginner framework, nor is it a framework built for generating standard copy-paste theme sites. I built this while working at a digital agency that did custom commissioned projects, and standard themes were not really an option when someone is paying $50k+ for a custom site.

Spike is open source, and it can be used any way that anyone wants, don't get me wrong. But I, as the author, did not give much attention to beginner users or themes, since these are not the purpose for which I wrote spike. Most of the community around spike, as far as I have been able to tell, is also made up of professionals building custom commissioned sites and apps.

If this is something you are interested in, by all means I would love to see you contribute towards this goal, and would be happy to help you along if I can answer questions. This is why open source is so great - it can be whatever you want it to be 😁 

I'm going to close, since this is more of a question, and not an issue or bug. Please feel free to continue discussing though!

**Comment by jbshirk** [comment]
Thanks for the pointers. Yeah, one of the reasons I wanted to learn spike instead of using those others, is their one-size-fits all assumption that everybody wants a blog.

**Comment by jescalan** [comment]
Quite reasonable, that's also a reason that I wrote it! Have you considered writing your own styling and markup for what you're working on, or open-sourcing your markup and making it a theme yourself?

**Comment by jbshirk** [comment]
I have so much to learn before I can do that, it would be premature to suggest I could.

**Comment by jescalan** [comment]
If that is the case, I'd definitely suggest passing on any sort of theme or build system and learning to write some quality html and css from the ground up 😁

**Comment by vanthome** [comment]
We use our [VCL Framework](http://vcl.github.io/) which supports theming and the [Webpack PostCSS loader](https://github.com/postcss/postcss-loader) and there you have theming in spike.
